### ISSUE TITLE
Add a Login With Github Button

### ISSUE THREAD

**Issue by jay-dee7** [guacamole/parachute-ui#12]
Since we already have plans for adding support for OAuth2, it'll be nice to have `Login With Github` option onto our site. 
It'll make the onboarding process super simple and since it's primarily dev focused, mostly people will have github account.

Github has amazing docs for integrating their OAuth into your application. More can be found here: https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps

**Comment by Mansihub** [comment]
Have you registered your website with Github oAuth? If that is the case,then i can try to add "login with Github" option onto your website

**Comment by guacamole** [comment]
Hello @Mansihub , so glad you showed interest in the project.
We have not really started on github Oauth, if you wish, please go ahead and work on it.
Although let me inform you in advance that we're not paying/sending rewards on contributions yet.
Let us know if you need help getting started with the feature.

**Comment by Mansihub** [comment]
Thanks! Do you want me to register your website with Github Oauth or anything else?For that i will be requiring some information like appication name,main url and callback url.
